# cloudbuild.yaml
steps:
  # Install dependencies
  - name: 'node:16'
    entrypoint: npm
    args: ['install']

  # Build the client app
  - name: 'node:16'
    entrypoint: npm
    args: ['run', 'build:client']
    env:
      - 'NODE_ENV=production'

  # Build the server app
  - name: 'node:16'
    entrypoint: npm
    args: ['run', 'build:api']
    env:
      - 'NODE_ENV=production'

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/auth-app', '.']

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/auth-app']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'auth-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/auth-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

