services:
  mongodb:
    image: mongo:latest
    container_name: auth-app-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-app-api
    environment:
      - NODE_ENV=development
      - PORT=3333
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/auth-app?authSource=admin
      - JWT_SECRET=your-secret-key
    ports:
      - "3333:3333"
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:
    name: auth-app-mongodb-data

networks:
  app-network:
    name: auth-app-network
